"""empty message

Revision ID: 8811628bd08e
Revises: a4b51348c7f3
Create Date: 2021-05-29 14:29:40.921518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8811628bd08e'
down_revision = 'a4b51348c7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_list_name'), ['name'], unique=False)

    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monster_name'), ['name'], unique=False)

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_name'), ['name'], unique=False)

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_title'), ['title'], unique=False)

    with op.batch_alter_table('ranking_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_player_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_player_name'))

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_title'))

    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_name'))

    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monster_name'))

    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_list_name'))

    # ### end Alembic commands ###
