"""empty message

Revision ID: a4b51348c7f3
Revises: b3b1e8b3df1f
Create Date: 2021-05-21 15:31:57.247909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b51348c7f3'
down_revision = 'b3b1e8b3df1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_build',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('character_class', sa.Enum('noble', 'magic_knight', 'court_magician', 'mercenary', 'gladiator', 'guardian_swordsman', 'saint', 'priest', 'shaman', 'explorer', 'excavator', 'sniper', name='characterclass'), nullable=False),
    sa.Column('build_hash', sa.String(length=128), nullable=False),
    sa.Column('build_title', sa.String(length=128), nullable=False),
    sa.Column('build_description', sa.Text(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_star',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['planner_build.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planner_star')
    op.drop_table('planner_build')
    # ### end Alembic commands ###
