"""empty message

Revision ID: b3b1e8b3df1f
Revises: c914a204cfb0
Create Date: 2021-01-08 14:16:37.873622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b1e8b3df1f'
down_revision = 'c914a204cfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_player',
    sa.Column('composite_key_string', sa.String(length=32), nullable=False),
    sa.Column('server', sa.Enum('luxplena', 'bergruen', name='server'), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('guild', sa.String(length=32), nullable=True),
    sa.Column('character_class', sa.Enum('noble', 'magic_knight', 'court_magician', 'mercenary', 'gladiator', 'guardian_swordsman', 'saint', 'priest', 'shaman', 'explorer', 'excavator', 'sniper', name='characterclass'), nullable=False),
    sa.Column('level_land', sa.Integer(), nullable=False),
    sa.Column('level_sea', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('server', 'name')
    )
    op.create_table('ranking_player_history',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server', sa.Enum('luxplena', 'bergruen', name='server'), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('previous_level_land', sa.Integer(), nullable=True),
    sa.Column('new_level_land', sa.Integer(), nullable=True),
    sa.Column('previous_level_sea', sa.Integer(), nullable=True),
    sa.Column('new_level_sea', sa.Integer(), nullable=True),
    sa.Column('previous_character_class', sa.Enum('noble', 'magic_knight', 'court_magician', 'mercenary', 'gladiator', 'guardian_swordsman', 'saint', 'priest', 'shaman', 'explorer', 'excavator', 'sniper', name='characterclass'), nullable=True),
    sa.Column('new_character_class', sa.Enum('noble', 'magic_knight', 'court_magician', 'mercenary', 'gladiator', 'guardian_swordsman', 'saint', 'priest', 'shaman', 'explorer', 'excavator', 'sniper', name='characterclass'), nullable=True),
    sa.Column('previous_guild', sa.String(length=16), nullable=True),
    sa.Column('new_guild', sa.String(length=16), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_player_history')
    op.drop_table('ranking_player')
    # ### end Alembic commands ###
