"""empty message

Revision ID: c914a204cfb0
Revises: ce103b12eed8
Create Date: 2021-01-03 11:56:08.129123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c914a204cfb0'
down_revision = 'ce103b12eed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_data',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('point_type', sa.String(length=32), nullable=False),
    sa.Column('character_class', sa.Enum('noble', 'magic_knight', 'court_magician', 'mercenary', 'gladiator', 'guardian_swordsman', 'saint', 'priest', 'shaman', 'explorer', 'excavator', 'sniper', name='characterclass'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('max_mp', sa.Integer(), nullable=False),
    sa.Column('avoidance', sa.Integer(), nullable=False),
    sa.Column('melee_min_attack', sa.Integer(), nullable=False),
    sa.Column('melee_max_attack', sa.Integer(), nullable=False),
    sa.Column('melee_hitrate', sa.Integer(), nullable=False),
    sa.Column('melee_critical_rate', sa.Integer(), nullable=False),
    sa.Column('range_min_attack', sa.Integer(), nullable=False),
    sa.Column('range_max_attack', sa.Integer(), nullable=False),
    sa.Column('range_hitrate', sa.Integer(), nullable=False),
    sa.Column('range_critical_rate', sa.Integer(), nullable=False),
    sa.Column('magic_min_attack', sa.Integer(), nullable=False),
    sa.Column('magic_max_attack', sa.Integer(), nullable=False),
    sa.Column('magic_hitrate', sa.Integer(), nullable=False),
    sa.Column('magic_critical_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_data')
    # ### end Alembic commands ###
