"""empty message

Revision ID: ce103b12eed8
Revises: f1b7b8a8c467
Create Date: 2020-12-27 16:56:58.385973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce103b12eed8'
down_revision = 'f1b7b8a8c467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster_skill', schema=None) as batch_op:
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('pet_skill', schema=None) as batch_op:
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('player_skill', schema=None) as batch_op:
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_skill', schema=None) as batch_op:
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('pet_skill', schema=None) as batch_op:
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('monster_skill', schema=None) as batch_op:
        batch_op.alter_column('cooldown',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cast_time',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
