"""empty message

Revision ID: f1b7b8a8c467
Revises: ba5689c4acfe
Create Date: 2020-12-27 16:56:11.023882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b7b8a8c467'
down_revision = 'ba5689c4acfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('pet_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('player_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('pet_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('monster_skill', schema=None) as batch_op:
        batch_op.alter_column('effect_range',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
