const weaponTables = [
  'cariad', 'rapier', 'dagger', 'one_handed_sword',
  'two_handed_sword', 'rifle', 'duals',
];
const armorTables = [
  'shield', 'pants', 'coat', 'shoes', 'gauntlet',
];
const shipTables = [
  'ship_body', 'ship_front', 'ship_head_mast', 'ship_main_mast',
  'ship_figure', 'ship_magic_stone', 'ship_anchor',
  'ship_normal_weapon', 'ship_special_weapon',
];

const effectCodes = [
  { label: 'Max. HP', value: 0 },
  { label: 'Max. MP', value: 1 },
  { label: 'HP. Recovery', value: 2 },
  { label: 'MP. Recovery', value: 3 },
  { label: 'Avoidance', value: 4 },
  { label: 'Movement Speed', value: 5 },
  { label: 'Melee Max. Attack', value: 6 },
  { label: 'Melee Min. Attack', value: 7 },
  { label: 'Range Max. Attack', value: 8 },
  { label: 'Range Min. Attack', value: 9 },
  { label: 'Magic Max. Attack', value: 10 },
  { label: 'Magic Min. Attack', value: 11 },
  { label: 'Physical Defense', value: 12 },
  { label: 'Magic Defense', value: 13 },
  { label: 'Melee Hitting', value: 14 },
  { label: 'Range Hitting', value: 15 },
  { label: 'Magic Hitting', value: 16 },
  { label: 'Melee Atk. Speed', value: 17 },
  { label: 'Range Akt. Speed', value: 18 },
  { label: 'Magic Akt. Speed', value: 19 },
  { label: 'Melee Akt. Range', value: 20 },
  { label: 'Range Akt. Range', value: 21 },
  { label: 'Magic Akt. Range', value: 22 },
  { label: 'Melee Critical Rate', value: 23 },
  { label: 'Range Critical Rate', value: 24 },
  { label: 'Magic Critical Rate', value: 25 },
  { label: null, value: 26 },
  { label: null, value: 27 },
  { label: null, value: 28 },
  { label: null, value: 29 },
  { label: null, value: 30 },
  { label: null, value: 31 },
  { label: null, value: 32 },
  { label: null, value: 33 },
  { label: null, value: 34 },
  { label: null, value: 35 },
  { label: null, value: 36 },
  { label: null, value: 37 },
  { label: null, value: 38 },
  { label: null, value: 39 },
  { label: null, value: 40 },
  { label: null, value: 41 },
  { label: null, value: 42 },
  { label: 'Total Attack', value: 43 },
  { label: null, value: 44 },
  { label: null, value: 45 },
  { label: null, value: 46 },
  { label: null, value: 47 },
  { label: null, value: 48 },
  { label: null, value: 49 },
  { label: null, value: 50 },
  { label: null, value: 51 },
  { label: null, value: 52 },
  { label: null, value: 53 },
  { label: null, value: 54 },
  { label: null, value: 55 },
  { label: null, value: 56 },
  { label: null, value: 57 },
  { label: null, value: 58 },
  { label: null, value: 59 },
  { label: null, value: 60 },
  { label: null, value: 61 },
  { label: null, value: 62 },
  { label: null, value: 63 },
  { label: null, value: 64 },
  { label: null, value: 65 },
  { label: null, value: 66 },
  { label: null, value: 67 },
  { label: null, value: 68 },
  { label: 'Recovery Skill Up', value: 69 },
  { label: null, value: 70 },
  { label: null, value: 71 },
  { label: null, value: 72 },
  { label: null, value: 73 },
  { label: null, value: 74 },
  { label: null, value: 75 },
  { label: null, value: 76 },
  { label: null, value: 77 },
  { label: null, value: 78 },
  { label: null, value: 79 },
  { label: null, value: 80 },
  { label: null, value: 81 },
  { label: null, value: 82 },
  { label: null, value: 83 },
  { label: null, value: 84 },
  { label: null, value: 85 },
  { label: null, value: 86 },
  { label: null, value: 87 },
  { label: null, value: 88 },
  { label: null, value: 89 },
  { label: null, value: 90 },
  { label: null, value: 91 },
  { label: null, value: 92 },
  { label: null, value: 93 },
  { label: null, value: 94 },
  { label: null, value: 95 },
  { label: null, value: 96 },
  { label: null, value: 97 },
  { label: null, value: 98 },
  { label: null, value: 99 },
  { label: null, value: 100 },
  { label: null, value: 101 },
  { label: null, value: 102 },
  { label: null, value: 103 },
  { label: null, value: 104 },
  { label: null, value: 105 },
  { label: null, value: 106 },
  { label: null, value: 107 },
  { label: null, value: 108 },
  { label: null, value: 109 },
  { label: null, value: 110 },
  { label: null, value: 111 },
  { label: null, value: 112 },
  { label: 'Land EXP', value: 113 },
  { label: 'Sea EXP', value: 114 },
  { label: null, value: 115 },
  { label: null, value: 116 },
  { label: 'Fishing Rate', value: 117 },
  { label: 'Fishing Bait Effectivity', value: 118 },
  { label: null, value: 119 },
  { label: null, value: 120 },
  { label: null, value: 121 },
  { label: null, value: 122 },
  { label: null, value: 123 },
  { label: null, value: 124 },
  { label: null, value: 125 },
  { label: 'All Stat', value: 126 },
  { label: null, value: 127 },
  { label: null, value: 128 },
  { label: 'All Attack', value: 129 },
  { label: 'All Defense', value: 130 },
  { label: 'Atk. Speed', value: 131 },
  { label: null, value: 132 },
  { label: null, value: 133 },
  { label: null, value: 134 },
  { label: null, value: 135 },
  { label: null, value: 136 },
  { label: null, value: 137 },
  { label: null, value: 138 },
  { label: null, value: 139 },
  { label: null, value: 140 },
  { label: null, value: 141 },
  { label: null, value: 142 },
  { label: null, value: 143 },
  { label: null, value: 144 },
  { label: null, value: 145 },
  { label: null, value: 146 },
  { label: null, value: 147 },
  { label: null, value: 148 },
  { label: null, value: 149 },
  { label: null, value: 150 },
  { label: null, value: 151 },
  { label: null, value: 152 },
  { label: null, value: 153 },
  { label: 'Fishing Time Decrease', value: 154 },
  { label: 'Constitution', value: 155 },
  { label: 'Strength', value: 156 },
  { label: 'Intelligence', value: 157 },
  { label: 'Dexterity', value: 158 },
  { label: 'Wisdom', value: 159 },
  { label: 'Will', value: 160 },
  { label: 'Luck', value: 161 },
  { label: null, value: 162 },
  { label: null, value: 163 },
  { label: null, value: 164 },
  { label: null, value: 165 },
  { label: null, value: 166 },
  { label: null, value: 167 },
  { label: null, value: 168 },
  { label: null, value: 169 },
  { label: null, value: 170 },
  { label: null, value: 171 },
  { label: null, value: 172 },
  { label: null, value: 173 },
];

export {
  weaponTables, armorTables, shipTables, effectCodes,
};
