import React, { useEffect } from 'react';
import { setWindowTitle } from '../../helpers';
import Prose from '../shared/Prose';

const LegalNotice = () => {
  useEffect(() => {
    setWindowTitle('Legal Notice');
  }, []);

  return (
    <Prose>
      <h1 className="sr-only">Legal Notice</h1>

      <h2>Contact Information</h2>
      <p>
        Jeremy Regitz
        <br />
        E-Mail:
        {' '}
        <a href="mailto:contact@flandria.info">contact@flandria.info</a>
        <br />
        Internet address:
        {' '}
        <a href="www.flandria.info" target="_blank">www.flandria.info</a>
      </p>

      <h2>Graphics and Image Sources</h2>
      <p>
        GiikuGames / AHA Entertainment
      </p>

      <h2>Disclaimer</h2>
      <h3>Accountability for content</h3>
      <p>
        The contents of our pages have been created with the utmost care. However, we cannot
        guarantee the contents&apos; accuracy, completeness or topicality. According to
        statutory provisions, we are furthermore responsible for our own content on
        these web pages. In this matter, please note that we are not obliged to monitor
        the transmitted or saved information of third parties, or investigate circumstances
        pointing to illegal activity. Our obligations to remove or block the use of information
        under generally applicable laws remain unaffected by this as per §§ 8 to 10 of the
        Telemedia Act (TMG).
      </p>

      <h3>Accountability for links</h3>
      <p>
        Responsibility for the content of external links (to web pages of third parties)
        lies solely with the operators of the linked pages. No violations were evident
        to us at the time of linking. Should any legal infringement become known to us
        we will remove the respectivelink immediately.
      </p>

      <h3>Copyright</h3>
      <p>
        Our web pages and their contents are subject to German copyright law. Unless
        expressly permitted by law, every form of utilizing, reproducing or processing
        works subject to copyright protection on our web pages requires the prior consent of
        the respective owner of the rights. Individual reproductions of a work are only
        allowed for private use. The materials from these pages are copyrighted and
        any unauthorized use may violate copyright laws.
      </p>

      <blockquote>
        Legal Notice generated by
        {' '}
        <a href="http://www.translate-24h.de">translate-24h.de</a>
      </blockquote>
    </Prose>
  );
};

export default LegalNotice;
